### ISSUE TITLE
doesn't work in win10

### ISSUE THREAD

**Issue by FirdousNath** [sindresorhus/taskkill#7] opened 2018-10-15 12:07 UTC
I need to run an app as an administrator than only processes are killed otherwise not

**Comment by MarkTiedemann** [comment] 2018-10-15 23:28
@FirdousNath I'm not quite sure what kind of problem you are having based on your description. Can you please try to explain your case in a bit more detail? Perhaps also add error messages or example code snippets if possible.

**Comment by FirdousNath** [comment] 2018-10-16 05:35
when I kill calculator via taskkill, it worked flawless in win7-8 but I need to run the app as an administrator to kill same calculator app in win10. Its not raising any error as such :(

**Comment by MarkTiedemann** [comment] 2018-10-16 10:51
I investigated your case a bit. Here's what I did:

0. Open the default command prompt (_not_ as an administrator).

```
[press Windows key]
[type cmd.exe]
[press Enter key]
```

1. Start the built-in Windows calculator app.

```
calc
```

2. Try to taskkill the calculator app.

```
taskkill /im calc.exe
ERROR: The process "calc.exe" not found.
```

3. Try to find the calculator app.

```
tasklist /fi "imageName eq calc*"

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
Calculator.exe                8940 Console                    3     55,488 K
```

It seems like the calculator image is not named `calc.exe` but `calculator.exe`. (This might be a change from Windows 8 to Windows 10, but I'm not sure.)

4. Try to kill `calculator.exe`.

```
taskkill /im calculator.exe
SUCCESS: Sent termination signal to the process "Calculator.exe" with PID 8940.
```

A termination signal was sent, but notice that the process has not been terminated. This means that the calculator app does not handle termination signals properly.

5. Force kill `calculator.exe`.

```
taskkill /im calculator.exe /f
SUCCESS: The process "Calculator.exe" with PID 8940 has been terminated.
```

Finally, the process of the calculator app has been terminated.

(Note: When using the Node.js `tasklist` wrapper, you'll have to set the `force` option to `true` to force kill.)

----

@FirdousNath Did this help to solve your issue?

**Comment by FirdousNath** [comment] 2018-10-16 11:16
@MarkTiedemann Thanks for your valuable time, but the problem is not with `keyword`. The same app kills _calculator_ when I run with administrator rights in `win10` as well. How will you signify this ?

**Comment by FirdousNath** [comment] 2018-10-16 13:06
My code is as below : 
`const taskkill = require('taskkill');`
```
taskkill(list, {force: true}).then(() => {
                                            console.log(`Successfully terminated ${list.join(', ')}`);
                                            list.slice(process.pid)
                                    });
```

list contains array of pid that i want to kill

**Comment by MarkTiedemann** [comment] 2018-10-16 17:54
I'm sorry, but I can't help you without further details.

There are system processes that you cannot kill at all or only when running as admin, by design. There are child processes that are created by Windows services which will simply respawn when you kill them. I can't tell what's going on in your case.

In any case, there's nothing I, as a maintainer of this module, can do to help you fix it. This module is simply a wrapper around the built-in `taskkill.exe`. If `taskkill.exe` can only kill that process as an admin, then there's nothing else we can do. I suppose you're gonna have to run your program as an admin.

Closing for now.

**Closed as completed by MarkTiedemann** 2018-10-16 17:54 UTC

**Comment by FirdousNath** [comment] 2018-10-17 06:08
thanks, highly appreciated your efforts :+1:
